apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:   
  - rhino-deployment.yaml
  - rhino-service.yaml
  - rhino-ingress.yaml
  - managed-cert.yaml
  - rhino-hpa.yaml
  #- rhino-secret.yaml
  #- rhino-configmap.yaml